# frozen_string_literal: true

source 'http://rubygems.org'

gem 'bundler'
gem 'cucumber'
gem 'cuke_modeler'
gem 'faker'
gem 'httparty'
gem 'json'
gem 'jsonpath'
gem 'json-schema'
gem 'mime-types'
gem 'net-ssh'
gem 'nokogiri'
gem 'os'
gem 'parallel_tests'
gem 'pry'
gem 'report_builder'
gem 'rspec'
gem 'rubocop'
gem 'tiny_tds'
gem 'write_xlsx'
